# Site settings
title: WebConfs - A blog about web conferences
email: oliverullman@gmail.com
description: A practice blog I created.
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: guilh
paginate: 3
gems: [jekyll-paginate]
# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
 -
   scope:
     path: "" # an empty string here means all files in the project
     type: "posts" #previously 'post' in Jekyll 2.2.
   values:
     author: Oliver Ullman
     layout: "post"
     category: conferences
     comments: true
 -
   scope:
     path: "" # an empty string here means all files in the project
     type: "pages" #previously 'post' in Jekyll 2.2.
   values:
     layout: "page"
